Repository UWindsor/vcar-web, pull requests merged in 2020-10, with the labels that each got.

#20 Sender email pass encryption
  .gitignore
  databases/auth_token.db
  main.py
  models/auth_token.py
  models/auth_token_db.py
  readme.md
  requirements.txt
  services/encrypt_helper.py
  services/function_helper.py
Labels: enhancement

#22 Vehicles endpoint
  databases/auth_token.db
  main.py
  models/auth_token.py
  models/auth_token_db.py
  models/vehicle_request.py
  services/function_helper.py
Labels: enhancement

#23 Bug fix
  .gitignore
  databases/auth_token.db
  logging/2020-10-15 22:54:02.311371.txt
  main.py
  services/function_helper.py
Labels: bug

#24 Ignore logging
  .gitignore
  logging/2020-10-15 22:54:02.311371.txt
  services/function_helper.py
Labels: bug, vcar-web
